# Copyright 2026 fitctl contributors
# SPDX-License-Identifier: Apache-2.0

from typing import Literal, Never, NotRequired, TypeAlias, TypedDict

JSONValue: TypeAlias = None | bool | int | float | str | list[JSONValue] | dict[str, JSONValue]
Verdict: TypeAlias = Literal["fit", "fit_with_degradation", "unfit", "indeterminate"]
__version__: str
core_version: str
semantic_encoding: str

class PathCheck(TypedDict):
    path_id: str
    path: str
    probe_links: NotRequired[bool]
    probe_health: NotRequired[bool]

class LinkPair(TypedDict):
    from_path_id: str
    to_path_id: str

def collect_survey() -> Artifact: ...
def replay_survey(fixtures_root: str, fixture_id: str) -> Artifact: ...
def replay_state(fixtures_root: str, fixture_id: str) -> Artifact: ...
def collect_state(*, path_checks: list[PathCheck] | None = None,
                  link_pairs: list[LinkPair] | None = None,
                  thermal_provider_config_paths: list[str] | None = None,
                  memory_reliability: bool = False, gpu_reliability: bool = False,
                  hardware_sensors: bool = False) -> Artifact: ...

class FitctlError(Exception): ...
class CoreError(FitctlError):
    error_model_id: str
    error_model_version: int
    reason_code: str
    checkpoint_id: str
    message: str
class DecodeError(FitctlError):
    error_model_id: str
    error_model_version: int
    reason_code: str
    checkpoint_id: str
    message: str
class SerializationError(FitctlError):
    error_model_id: str
    error_model_version: int
    reason_code: str
    checkpoint_id: str
    message: str
class NativeError(FitctlError):
    error_model_id: str
    error_model_version: int
    reason_code: str
    checkpoint_id: str
    message: str

class Artifact:
    def __new__(cls, _unavailable: Never) -> Never: ...
    @classmethod
    def from_dict(cls, data: dict[str, JSONValue]) -> Artifact: ...
    @classmethod
    def from_json(cls, text: str) -> Artifact: ...
    @property
    def schema_id(self) -> str: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def artifact_id(self) -> str: ...
    @property
    def verdict(self) -> Verdict | None: ...
    @property
    def primary_reason_code(self) -> str | None: ...
    def to_dict(self) -> dict[str, JSONValue]: ...
    def to_json(self) -> str: ...
    def semantic_hash(self) -> str: ...
    def semantic_bytes(self) -> bytes: ...
    def redact(self, profile: str, *, at: str) -> Artifact: ...

class Policy:
    def __new__(cls, _unavailable: Never) -> Never: ...
    @classmethod
    def from_dict(cls, data: dict[str, JSONValue]) -> Policy: ...
    @classmethod
    def from_json(cls, text: str) -> Policy: ...
    def to_dict(self) -> dict[str, JSONValue]: ...
    def to_json(self) -> str: ...

def builtin_config(category: str, config_id: str) -> dict[str, JSONValue]: ...

class BatchReport:
    def __new__(cls, _unavailable: Never) -> Never: ...
    @classmethod
    def from_dict(cls, data: dict[str, JSONValue]) -> BatchReport: ...
    @classmethod
    def from_json(cls, text: str) -> BatchReport: ...
    @property
    def schema_id(self) -> str: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def artifact_id(self) -> str: ...
    @property
    def rows(self) -> list[dict[str, JSONValue]]: ...
    @property
    def contract_summaries(self) -> list[dict[str, JSONValue]]: ...
    @property
    def service_profile_summaries(self) -> list[dict[str, JSONValue]]: ...
    def to_dict(self) -> dict[str, JSONValue]: ...
    def to_json(self) -> str: ...
    def export_csv(self, view: Literal["rows_csv", "contract_summary_csv", "service_profile_summary_csv"]) -> str: ...

def classify_batch(contracts: list[Artifact], profiles: list[Artifact], *, at: str,
                   mode: Literal["contract_only", "state_advisory", "state_required"] = "contract_only",
                   states: list[Artifact] | None = None,
                   max_state_age_seconds: int | None = None) -> BatchReport: ...

def derive_contract(survey: Artifact, policy: Policy, *, at: str,
                    extension_packs: list[dict[str, JSONValue]] | None = None,
                    invocation_context: dict[str, JSONValue] | None = None,
                    notes: str | None = None) -> Artifact: ...
def validate(contract: Artifact, profile: Artifact, *, at: str,
             mode: Literal["contract_only", "state_advisory", "state_required"] = "contract_only",
             state: Artifact | None = None, thermal_evidence: list[Artifact] | None = None,
             max_state_age_seconds: int | None = None, notes: str | None = None) -> Artifact: ...
